
import sys
sys.path.insert(0, r'D:\32685\code\MCModTrans')
from pathlib import Path

body = []
def L(s=''):
    body.append(s)

# Note: use \n in raw strings for literal backslash-n in output

L('"""Translation pipeline module.')
L('')
L('Extracted from cli.py translate() to enable reuse and testing.')
L('"""')
L('')
L('from __future__ import annotations')
L('import asyncio, logging, time')
L('from dataclasses import dataclass')
L('from pathlib import Path')
L('from typing import Callable')
L('from .config import AppConfig')
L('from .models import PipelineReport')
L('logger = logging.getLogger(__name__)')
L('')
L('class _NoOpCache:')
L('    def __enter__(self): return self')
L('    def __exit__(self, *a): pass')
L('    @staticmethod')
L('    def get(j): return None')
L('    @staticmethod')
L('    def put(j,a): pass')
L('')
L('@dataclass')
L('class TranslationOutput:')
L('    translated_mods: list')
L('    report: PipelineReport')
L('    tm_hits: dict')
L('    mc_version: str')
L('')
L('def _resolve_mods_path(path: Path):')
L('    mods_subdir = path / "mods"')
L('    if mods_subdir.is_dir():')
L('        jars = list(mods_subdir.glob("*.jar"))')
L('        if jars:')
L('            return mods_subdir, _detect_mc_version(path)')
L('    if list(path.glob("*.jar")):')
L('        return path, _detect_mc_version(path)')
L('    return path, ""')
L('')
L('def _detect_mc_version(pack_root: Path) -> str:')
L('    import json')
L('    jp = pack_root / (pack_root.name + ".json")')
L('    if not jp.is_file():')
L('        for c in sorted(pack_root.glob("*.json")):')
L('            if c.stem not in ("options", "pack"): jp = c; break')
L('    try:')
L('        d = json.loads(jp.read_text(encoding="utf-8"))')
L('        return d.get("clientVersion") or d.get("inheritsFrom") or d.get("assetIndex",{}).get("id","")')
L('    except Exception: return ""')

content = chr(10).join(body)
Path(r'D:\32685\code\MCModTrans\modtrans\pipeline.py').write_text(content, encoding='utf-8')
print('OK', len(body), 'lines')
